version: '2'
services:
  web:
    build: ./web
    hostname: web
    volumes:
      - ./web/app:/app
      - ./archive:/archive
      - ./scripts:/scripts
    ports:
      - "5555:5555"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=${FLASK_DEBUG}
      - FLASK_KEY=${FLASK_KEY}
      - PYTHONUNBUFFERED=1
      - 'RUN=flask run --host=0.0.0.0 --port=5555'
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
    command: flask run --host=0.0.0.0 --port=5555
    depends_on:
      - "mq"
    restart: always
    networks:
      - warcnet
  mq:
    image: rabbitmq:3.7.6-alpine
    hostname: mq
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
    volumes:
        - ./queue:/q
    ports:
      - "15672"
      - "5672"
    restart: always
    networks:
      - warcnet
  worker:
    build: ./worker
    hostname: worker
    volumes:
      - ./archive:/archive
      - ./scripts:/scripts
    environment:
      - PYTHONUNBUFFERED=1
      - ERROR_EMAIL=${ERROR_EMAIL}
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}
      - INDOCKER=true
    depends_on:
      - "mq"
    restart: always
    shm_size: 1G
    networks:
      - warcnet
#  playback:
#    build: ./playback
#    hostname: playback
#    volumes:
#      - ./archive:/archive
#      - ./playback/webarchive:/webarchive
#    environment:
#      - PYTHONUNBUFFERED=1
#      - ERROR_EMAIL=${ERROR_EMAIL}
#    depends_on:
#      - "web"
#    restart: always
#    networks:
#      - warcnet
networks:
  warcnet:
    driver: bridge
